# Generated by Django 5.2.9 on 2025-12-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
