# Generated by Django 5.2.9 on 2026-01-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
