# Generated by Django 5.2.9 on 2026-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.CharField(blank=True, default='01.01.2025', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default=None, max_length=14, null=True),
        ),
    ]
