# Generated by Django 5.2.9 on 2026-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_dob_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
