# Generated by Django 5.2.9 on 2026-01-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_gender_employee_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Gender',
            new_name='gender',
        ),
    ]
